[package]
name = "runeweaver-benchmarks"
version = "0.0.0"
edition = "2024"
publish = false
rust-version = "1.86"

[workspace]

[dev-dependencies]
criterion = "0.8.2"
quote = "1"
runeweaver = { path = "../runeweaver" }
runeweaver-codegen = { path = "../runeweaver-codegen" }
syn = "2"

[[bench]]
name = "callbacks"
harness = false

[[bench]]
name = "java_like"
harness = false

[[bench]]
name = "json"
harness = false

[[bench]]
name = "keywords"
harness = false

[[bench]]
name = "lisp_like"
harness = false

[[bench]]
name = "modes"
harness = false

[[bench]]
name = "payloads"
harness = false

[[bench]]
name = "punctuation"
harness = false

[[bench]]
name = "rust_like"
harness = false

[[bench]]
name = "small"
harness = false

[[bench]]
name = "transitions"
harness = false

[[bench]]
name = "xml"
harness = false

[lints.rust]
unsafe_code = "forbid"
